config/routes.rb
Rails.application.routes.draw do
  get 'admin_problems/index'
  get 'admin_users/index'
  resources :messages
  resources :conversations
  get 'chats/index'
  get 'rooms/index'
  resources :chats
  resources :users
  resources :rooms
  resources :tags
  resources :rooms
  resources :themes
  resources :problems
  resources :taggings
  get 'admin', to: 'admin_users#index'
  get 'admin_problems', to: 'admin_problems#index'
  root 'admin_users#index'
  get 'issues/index'
  get 'issues/create'
  get 'users/login'
  get 'issues/update'
  # get 'tags/:tag', to: 'users#index', as: :tag
  get 'issues/destroy'
  get 'themes/index'
  get 'conversations/index'
  get 'tags/index'

  resources :troubles
  
  resources :issues

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :troubles, only: %i[index show]
    end
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :taggings, only: %i[index show]
    end
  end
  
  resources :rooms do
    resources :messages
  end

  scope '/api/v2' do 
    resources :issues
end

  scope :api, defaults: { format: :json } do
    scope :v1 do
      resources :users, only: %i[index show]
      resources :rooms do
        resources :messages
      end
      devise_for :users, defaults: { format: :json }, path: '', path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        registration: 'signup'
      },
      
      controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_chats, -> { where(is_private: false) }
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, scope: :recipient_id
    scope :between, -> (sender_id, recipient_id) do 
      where("(conversations.sender_id = ? AND   conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
    end
  end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, -> { where(is_private: false) }
    after_create_commit {broadcast_append_to "rooms"}
    has_many :messages
  end

app/models/supper.rb
class Supper < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :users, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :user
end

app/models/theme.rb
class Theme < ApplicationRecord
    belongs_to :user
end

app/models/trouble.rb
class Trouble < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord

  has_many :taggings
  has_many :tags, through: :taggings
  has_many :messages

  def self.tagged_with(name)
    Tag.find_by!(name: name).users
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
 
  mount_uploader :image, ImageUploader
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :registerable, :validatable,
         :jwt_authenticatable, :recoverable, :rememberable, jwt_revocation_strategy: self    
         after_create_commit { broadcast_append_to "users" }       
end

app/controllers/troubles_controller.rb
class TroublesController < ApplicationController
  before_action :set_trouble, only: %i[ show edit update destroy ]
  respond_to :json
  # GET /troubles or /troubles.json
  def index
    troubles = Trouble.all
    if troubles
      render json: {status: "SUCCESS", message: "All users ready", data: troubles}, status: :ok
    else
      render json: troubles.errors, status: :bad_request
    end

    # online = User.all.find_by_jti(params[:jti])
  end

  # GET /troubles/1 or /troubles/1.json
  def show
  end

  # GET /troubles/new
  def new
    @trouble = Trouble.new
  end

  # GET /troubles/1/edit
  def edit
  end

  # POST /troubles or /troubles.json
  def create
    @trouble = Trouble.new(trouble_params)

    respond_to do |format|
      if @trouble.save
        format.html { redirect_to admin_problems_url  }
        format.json { render :show, status: :created, location: @trouble }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trouble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /troubles/1 or /troubles/1.json
  def update
    respond_to do |format|
      if @trouble.update(trouble_params)
        format.html { redirect_to admin_problems_url }
        format.json { render :show, status: :ok, location: @trouble }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trouble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /troubles/1 or /troubles/1.json
  def destroy
    @trouble.destroy

    respond_to do |format|
      format.html { redirect_to admin_problems_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trouble
      @trouble = Trouble.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trouble_params
      params.require(:trouble).permit(:name, :display_in_navbar)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/troubles_helper.rb
module TroublesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/troubles/_form.html.erb
<%= form_with(model: trouble) do |form| %>
  <% if trouble.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trouble.errors.count, "error") %> prohibited this trouble from being saved:</h2>

      <ul>
        <% trouble.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="placeholder">
    <%= form.text_field :name, placeholder: "Введите имя проблемы..." %>
  </div>

 

  <div>
    <%= form.submit "Сохранить" %>
  </div>
<% end %>

app/views/troubles/_trouble.html.erb
<div id="<%= dom_id trouble %>">
  <p>
    <strong>Name:</strong>
    <%= trouble.name %>
  </p>

  <p>
    <strong>Display in navbar:</strong>
    <%= trouble.display_in_navbar %>
  </p>

</div>

app/views/troubles/edit.html.erb
<div class="header">
<div class="left--header">

<%= link_to 'Проблемы', admin_problems_path, class: "text" %>
<%= link_to 'Пользователи', admin_path, class: "opacity" %>

</div>
<div class="right--header">
<p class="text"> Admin </p>
</div>
</div>
<div class="block--center">

  <div class="h1">Редактирование проблемы</div>

  <%= render "form", trouble: @trouble %>
</div>
<br>

 <%= link_to image_tag("back.svg"), admin_problems_path, class:"back_icon"  %>
  <%= link_to "Назад", admin_problems_path, class:"back" %>

app/views/troubles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Troubles</h1>

<div id="troubles">
  <% @troubles.each do |trouble| %>
    <%= render trouble %>
    <p>
      <%= link_to "Show this trouble", trouble %>
    </p>
  <% end %>
</div>

<%= link_to "New trouble", new_trouble_path %>

app/views/troubles/new.html.erb
<div class="header">
<div class="left--header">

<%= link_to 'Проблемы', admin_problems_path, class: "text" %>
<%= link_to 'Пользователи', admin_path, class: "opacity" %>

</div>
<div class="right--header">
<p class="text"> Admin </p>
</div>
</div>
<div class="block--center">
    <h1 class="h11">Создание проблемы</h1>

    <%= render "form", trouble: @trouble %>
</div>
<br>

 <%= link_to image_tag("back.svg"), admin_problems_path, class:"back_icon"  %>
  <%= link_to "Назад", admin_problems_path, class:"back" %>

app/views/troubles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trouble %>

<div>
  <%= link_to "Edit this trouble", edit_trouble_path(@trouble) %> |
  <%= link_to "Back to troubles", admin_problems_path %>

  <%= button_to "Destroy this trouble", @trouble, method: :delete %>
</div>